services:
  db:
    build:
      context: .
      dockerfile: ./postgres-init/Dockerfile
    env_file: .env
    networks:
      - appnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_2: ${POSTGRES_DB_2}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB && pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB_2"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 7s

  app:
    build:
      context: .
      dockerfile: ./1/Dockerfile
    env_file: .env
    networks:
      - appnet
    ports:
      - "${PORT_APP}:8080"

  app2:
    build:
      context: .
      dockerfile: ./2/Dockerfile
    env_file: .env
    networks:
      - appnet
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT_APP2}:8080"

  app3:
    build:
      context: .
      dockerfile: ./3/Dockerfile
    networks:
      - appnet
    env_file: .env
    ports:
      - "${PORT_APP3}:8080"

  app4:
    build:
      context: .
      dockerfile: ./4/junior/Dockerfile
    env_file: .env
    networks:
      - appnet
    ports:
      - "${PORT_APP4}:8080"

  app5:
    build:
      context: .
      dockerfile: ./4/middle/Dockerfile
    env_file: .env
    networks:
      - appnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB_2}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT_APP5}:8080"

networks:
  appnet:
    driver: bridge
